# usage: amlt run caption_webvid.yaml
description: avl experiment

target:
  service: amlk8s
  name: itphyperdgx2cl1
  vc: hai7 

environment:
  image: avl:v1
  username: stevenml
  registry: stevenml.azurecr.io

code:
  local_dir: $CONFIG_DIR/LAVIS

storage:
  datasets: 
    storage_account_name: steven
    container_name: openaiminecraft
    mount_dir: /mnt/datasets_mnt
    mount_options: ["-o", "attr_timeout=240", "-o", "entry_timeout=240", "-o", "negative_timeout=120", "-o", "allow_other"]
    local_dir: /mnt/datasets_mnt

# list of jobs to run, we run 1 job in this example
jobs:
- name: AVL
  sku: 2xG16 # Use 1 16 GPU node, for 2 nodes do 2xG16, for 4 nodes do 4xG16
  mpi: False
  process_count_per_node: 16
  preemptible: False # Makes it so that your code is not interrupted.  If debugging, can set to True so that it runs faster or if all the non-preemptible (NP) nodes are already taken.
  command:
  - python train.py --cfg-path lavis/projects/avl/avl_small.yaml